---
- name: Deploy listener configuration
  template:
    src: 99-remote-collector.conf.j2
    dest: /etc/rsyslog.d/99-remote-collector.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart rsyslog

- name: Ensure rsyslog is enabled and running
  service:
    name: rsyslog
    state: started
    enabled: true

- name: Open firewall port (firewalld)
  ansible.posix.firewalld:
    port: "{{ rsyslog_listener_port }}/{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ rsyslog_listener_proto }}"
  when: rsyslog_configure_firewall | bool
  notify: reload firewalld
